---
# Import DurvalCRM Custom Theme to Keycloak
# Note: keycloak_http_port and keycloak_https_port are now defined as host variables in inventory/hosts.ini
# - vm-dev: keycloak_http_port=8090, keycloak_https_port=9443
# - vm-staging/production: keycloak_http_port=8090, keycloak_https_port=9443
- name: Import DurvalCRM Custom Theme to Keycloak
  hosts: vm-dev
  become: yes

  tasks:
    - name: Set Keycloak port based on environment
      set_fact:
        keycloak_active_port: "{{ keycloak_http_port if 'vm-dev' in group_names else keycloak_https_port }}"
        keycloak_protocol: "{{ 'http' if 'vm-dev' in group_names else 'https' }}"

    # Deploy Custom Keycloak Theme
    - name: Create Keycloak themes directory
      file:
        path: /opt/keycloak/themes
        state: directory
        owner: keycloak
        group: keycloak
        mode: '0755'

    - name: Copy DurvalCRM custom theme to Keycloak
      copy:
        src: ../../../durvalcrm-keycloak-theme/durvalcrm/
        dest: /opt/keycloak/themes/durvalcrm/
        owner: keycloak
        group: keycloak
        mode: '0644'
        directory_mode: '0755'

    - name: Set proper permissions for theme resources
      file:
        path: /opt/keycloak/themes/durvalcrm
        state: directory
        owner: keycloak
        group: keycloak
        mode: '0755'
        recurse: yes

    - name: Restart Keycloak to load custom theme
      systemd:
        name: keycloak
        state: restarted

    - name: Wait for Keycloak to restart and be available
      wait_for:
        port: "{{ keycloak_active_port }}"
        host: "127.0.0.1"
        timeout: 120
        delay: 10
      register: keycloak_restart_check

    - name: Verify Keycloak is responding after theme deployment
      uri:
        url: "{{ keycloak_base_url }}/realms/master"
        method: GET
        validate_certs: false
        status_code: 200
        timeout: 30
      register: keycloak_theme_health_check
      retries: 3
      delay: 10
      until: keycloak_theme_health_check is succeeded
      ignore_errors: true

    - name: Display theme deployment status
      debug:
        msg: |
          ========================================
          DurvalCRM Custom Theme Deployment:
          ----------------------------------------
          ✓ Theme deployed to: /opt/keycloak/themes/durvalcrm/
          ✓ Keycloak service restarted successfully
          ✓ Environment: {{ 'Development (HTTP)' if 'vm-dev' in group_names else 'Production (HTTPS)' }}
          ✓ Active Port: {{ keycloak_active_port }}
          ✓ Health Check: {{ 'Success' if keycloak_theme_health_check is succeeded else 'Failed - manual verification needed' }}
          
          To activate the theme:
          1. Access Keycloak Admin Console: {{ keycloak_base_url }}/admin/
          2. Navigate to: Realm Settings → Themes
          3. Set Login Theme: "durvalcrm"
          4. Save configuration
          ========================================